#!/bin/sh
gcc NvGpuCodec.cpp -o MTGpuFramework -O0 -g -std=c++11 -I. -I../boost_1_64_0/ -I./cuda/include/ -I../ffmpeg-3.3.2/ -L./ffmpeg -L./boost -L./cuda/lib64 -lnvcuvid -lcudart -lcuda -lavformat -lavcodec -lavutil -lswscale -lswresample -lboost_thread -lboost_filesystem -lboost_chrono -lboost_system -lpthread -lm -lstdc++ -ldl

scp ./MTGpuFramework root@192.168.105.224:/root/lxf
